import jsPDF from 'jspdf';
import { formatNumber, formatCurrency, formatAutonomy } from '../utils.js';

const TEAL = [0, 195, 201];
const DARK_BG = [9, 9, 11];
const SURFACE = [15, 15, 17];
const ELEVATED = [24, 24, 28];
const TEXT_PRIMARY = [240, 240, 245];
const TEXT_SECONDARY = [160, 160, 175];
const TEXT_MUTED = [100, 100, 115];
const BORDER = [40, 40, 48];
const ROW_ALT = [14, 14, 18];

const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN = 20;
const CONTENT_W = PAGE_W - MARGIN * 2;

function fillPageBg(doc) {
  doc.setFillColor(...DARK_BG);
  doc.rect(0, 0, PAGE_W, PAGE_H, 'F');
}

function addPageFooter(doc, pageNum) {
  doc.setFontSize(8);
  doc.setTextColor(...TEXT_MUTED);
  doc.text('Generated by Solisys v2.0', MARGIN, PAGE_H - 10);
  doc.text(`Page ${pageNum}`, PAGE_W - MARGIN, PAGE_H - 10, { align: 'right' });
  doc.text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), PAGE_W / 2, PAGE_H - 10, { align: 'center' });
}

function checkPageBreak(doc, y, needed, pageNum) {
  if (y + needed > PAGE_H - 25) {
    addPageFooter(doc, pageNum);
    doc.addPage();
    pageNum++;
    fillPageBg(doc);
    return { y: MARGIN + 5, pageNum };
  }
  return { y, pageNum };
}

function drawSectionHeader(doc, title, y, pageNum) {
  const check = checkPageBreak(doc, y, 16, pageNum);
  y = check.y;
  pageNum = check.pageNum;

  doc.setFillColor(...TEAL);
  doc.rect(MARGIN, y, 3, 10, 'F');
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...TEXT_PRIMARY);
  doc.text(title, MARGIN + 8, y + 8);
  return { y: y + 18, pageNum };
}

function drawKeyValue(doc, label, value, x, y, labelWidth) {
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...TEXT_MUTED);
  doc.text(label, x, y);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...TEXT_PRIMARY);
  doc.text(String(value), x + (labelWidth || 50), y);
}

function drawTable(doc, headers, rows, y, pageNum) {
  const colWidths = headers.map(() => CONTENT_W / headers.length);
  const rowHeight = 8;
  let startX = MARGIN;

  const check = checkPageBreak(doc, y, rowHeight * (rows.length + 1) + 4, pageNum);
  y = check.y;
  pageNum = check.pageNum;

  doc.setFillColor(...TEAL);
  doc.rect(MARGIN, y, CONTENT_W, rowHeight, 'F');
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...DARK_BG);
  headers.forEach((h, i) => {
    doc.text(h, startX + colWidths.slice(0, i).reduce((a, b) => a + b, 0) + 3, y + 5.5);
  });
  y += rowHeight;

  rows.forEach((row, rowIdx) => {
    const pb = checkPageBreak(doc, y, rowHeight, pageNum);
    y = pb.y;
    pageNum = pb.pageNum;

    if (rowIdx % 2 === 0) {
      doc.setFillColor(...ELEVATED);
      doc.rect(MARGIN, y, CONTENT_W, rowHeight, 'F');
    } else {
      doc.setFillColor(...SURFACE);
      doc.rect(MARGIN, y, CONTENT_W, rowHeight, 'F');
    }

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...TEXT_SECONDARY);
    row.forEach((cell, i) => {
      doc.text(String(cell), startX + colWidths.slice(0, i).reduce((a, b) => a + b, 0) + 3, y + 5.5);
    });
    y += rowHeight;
  });

  return { y: y + 4, pageNum };
}

export function downloadPDF(project, calculations, selectedPanel, selectedInverter, selectedBattery) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  let y = 0;
  let pageNum = 1;

  fillPageBg(doc);

  doc.setFillColor(...SURFACE);
  doc.rect(0, 0, PAGE_W, 70, 'F');

  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...TEAL);
  doc.text('SOLISYS', PAGE_W / 2, 30, { align: 'center' });

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...TEXT_MUTED);
  doc.text('Solar System Design Report', PAGE_W / 2, 40, { align: 'center' });

  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...TEXT_PRIMARY);
  doc.text(project.projectName || 'Untitled Project', PAGE_W / 2, 55, { align: 'center' });

  if (project.clientName) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...TEXT_SECONDARY);
    doc.text(`Client: ${project.clientName}`, PAGE_W / 2, 63, { align: 'center' });
  }

  doc.setFillColor(...TEAL);
  doc.rect(0, 70, PAGE_W, 2, 'F');

  y = 82;

  const systemType = project.systemType || 'off-grid';
  const systemTypeLabel = systemType === 'grid-tied' ? 'Grid-Tied' : systemType === 'hybrid' ? 'Hybrid' : 'Off-Grid';

  doc.setFillColor(...TEAL);
  doc.rect(MARGIN, y - 2, 3, 10, 'F');
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...TEXT_PRIMARY);
  doc.text('System Summary', MARGIN + 8, y + 6);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...TEAL);
  doc.text(`System Type: ${systemTypeLabel}`, PAGE_W - MARGIN, y + 6, { align: 'right' });
  y += 16;

  const panelW = selectedPanel ? selectedPanel.pmax : (project.panelWattage || 0);
  const panelLabel = selectedPanel ? `${selectedPanel.manufacturer} ${selectedPanel.model}` : `${panelW}W Panel`;
  const invKva = selectedInverter ? selectedInverter.ratedKva : (project.selectedInverterKva || calculations.recommendedInverterKva || 0);
  const invLabel = selectedInverter ? `${selectedInverter.manufacturer} ${selectedInverter.model}` : '';
  const battLabel = selectedBattery ? `${selectedBattery.manufacturer} ${selectedBattery.model}` : '';

  const summaryRows = [
    { label: 'SOLAR ARRAY', items: [
      { k: 'Total Array', v: `${formatNumber(calculations.actualArrayKw, 2)} kW` },
      { k: 'Panels', v: `${calculations.numberOfPanels} × ${panelW}W` },
      { k: 'Panel', v: panelLabel },
    ]},
    { label: 'BATTERY BANK', items: [
      { k: 'Capacity', v: `${formatNumber(calculations.requiredBankCapacityWh / 1000, 1)} kWh (${formatNumber(calculations.requiredBankCapacityAh, 0)} Ah)` },
      { k: 'Batteries', v: `${calculations.totalNumberOfBatteries} units` },
      { k: 'Configuration', v: calculations.batteriesInSeries > 0 ? `${calculations.batteriesInSeries}S × ${calculations.numberOfParallelStrings}P` : '—' },
      ...(battLabel ? [{ k: 'Model', v: battLabel }] : []),
    ]},
    { label: 'INVERTER', items: [
      { k: 'Size', v: `${formatNumber(invKva, 1)} kVA` },
      ...(invLabel ? [{ k: 'Model', v: invLabel }] : []),
      { k: 'Type', v: project.hasBuiltInController ? 'Hybrid (Built-in MPPT)' : 'Standalone' },
    ]},
    { label: 'LOAD & SYSTEM', items: [
      { k: 'Daily Load', v: `${formatNumber(calculations.totalDailyKwh, 2)} kWh` },
      { k: 'Peak Load', v: `${formatNumber(calculations.estimatedPeakLoadW, 0)} W` },
      { k: 'System Voltage', v: `${project.batteryVoltage}V DC` },
      { k: 'Autonomy', v: formatAutonomy(project.daysOfAutonomy) },
    ]},
  ];

  const halfW = CONTENT_W / 2;
  summaryRows.forEach((section, sIdx) => {
    const col = sIdx % 2;
    const isNewRow = col === 0;
    const baseX = MARGIN + col * halfW;
    const blockH = 6 + section.items.length * 6 + 4;

    if (isNewRow) {
      const otherSection = summaryRows[sIdx + 1];
      const otherH = otherSection ? 6 + otherSection.items.length * 6 + 4 : 0;
      const maxH = Math.max(blockH, otherH);
      const pb = checkPageBreak(doc, y, maxH, pageNum);
      y = pb.y;
      pageNum = pb.pageNum;

      doc.setFillColor(...ELEVATED);
      doc.rect(MARGIN, y - 2, CONTENT_W, maxH, 'F');
      doc.setDrawColor(...BORDER);
      doc.rect(MARGIN, y - 2, CONTENT_W, maxH, 'S');
    }

    let ly = y;
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...TEAL);
    doc.text(section.label, baseX + 5, ly + 2);
    ly += 6;

    section.items.forEach((item) => {
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...TEXT_MUTED);
      doc.text(item.k + ':', baseX + 5, ly + 2);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...TEXT_PRIMARY);
      doc.text(item.v, baseX + 38, ly + 2);
      ly += 6;
    });

    if (col === 1) {
      const thisH = 6 + section.items.length * 6 + 4;
      const prevH = 6 + summaryRows[sIdx - 1].items.length * 6 + 4;
      y += Math.max(thisH, prevH);
    }
  });

  if (summaryRows.length % 2 !== 0) {
    const lastSection = summaryRows[summaryRows.length - 1];
    y += 6 + lastSection.items.length * 6 + 4;
  }

  y += 4;

  const sep = () => {
    doc.setDrawColor(...BORDER);
    doc.line(MARGIN, y, PAGE_W - MARGIN, y);
    y += 6;
  };

  sep();

  const sh = (title) => {
    const result = drawSectionHeader(doc, title, y, pageNum);
    y = result.y;
    pageNum = result.pageNum;
  };

  sh('Load Analysis');

  const loadMethod = project.calcMethod === 'audit' ? 'Appliance Audit' : 'Manual Entry';
  drawKeyValue(doc, 'Method:', loadMethod, MARGIN + 4, y, 35);
  y += 8;
  drawKeyValue(doc, 'Daily Energy:', `${formatNumber(calculations.totalDailyKwh, 2)} kWh (${formatNumber(calculations.totalDailyWh, 0)} Wh)`, MARGIN + 4, y, 35);
  y += 8;
  drawKeyValue(doc, 'Peak Load:', `${formatNumber(calculations.estimatedPeakLoadW, 0)} W`, MARGIN + 4, y, 35);
  y += 6;

  if (project.calcMethod === 'audit' && project.appliances && project.appliances.length > 0) {
    y += 2;
    const appRows = project.appliances
      .filter(a => a.name && a.watts > 0)
      .map(a => [
        a.name,
        `${a.watts}W`,
        `${a.quantity}`,
        `${a.hoursPerDay}h`,
        `${formatNumber(a.watts * a.quantity * a.hoursPerDay, 0)} Wh`,
      ]);

    if (appRows.length > 0) {
      const result = drawTable(doc, ['Appliance', 'Watts', 'Qty', 'Hours/Day', 'Daily Wh'], appRows, y, pageNum);
      y = result.y;
      pageNum = result.pageNum;
    }
  }

  sep();

  sh('Solar Array');

  const arrayRows = [
    ['Panel', panelLabel],
    ['Panel Wattage', `${panelW}W`],
    ['Number of Panels', `${calculations.numberOfPanels}`],
    ['Required Array', `${formatNumber(calculations.requiredPanelWattageTotal / 1000, 2)} kW`],
    ['Actual Array', `${formatNumber(calculations.actualArrayKw, 2)} kW`],
    ['Peak Sun Hours', `${project.peakSunHours} hrs`],
    ['System Efficiency', `${project.systemEfficiency}%`],
  ];

  if (calculations.numberOfStrings > 0) {
    arrayRows.push(['Strings', `${calculations.numberOfStrings} parallel`]);
    arrayRows.push(['Panels per String', `${project.panelsPerString || calculations.panelsPerStringMin}`]);
  }

  arrayRows.forEach(([label, value]) => {
    const pb = checkPageBreak(doc, y, 8, pageNum);
    y = pb.y;
    pageNum = pb.pageNum;
    drawKeyValue(doc, `${label}:`, value, MARGIN + 4, y, 50);
    y += 7;
  });

  y += 2;
  sep();

  sh('Battery Bank');

  const batteryLabel = battLabel || `${project.availableBatteryAh}Ah ${project.availableBatteryVoltage}V`;
  const batteryRows = [
    ['Battery', batteryLabel],
    ['System Voltage', `${project.batteryVoltage}V DC`],
    ['Backup Duration', formatAutonomy(project.daysOfAutonomy)],
    ['Battery DoD', `${(project.batteryDoD * 100).toFixed(0)}%`],
    ['Required Capacity', `${formatNumber(calculations.requiredBankCapacityWh, 0)} Wh (${formatNumber(calculations.requiredBankCapacityAh, 0)} Ah)`],
    ['Total Batteries', `${calculations.totalNumberOfBatteries} units`],
    ['Configuration', `${calculations.batteriesInSeries}S × ${calculations.numberOfParallelStrings}P`],
  ];

  batteryRows.forEach(([label, value]) => {
    const pb = checkPageBreak(doc, y, 8, pageNum);
    y = pb.y;
    pageNum = pb.pageNum;
    drawKeyValue(doc, `${label}:`, value, MARGIN + 4, y, 50);
    y += 7;
  });

  y += 2;
  sep();

  sh('Inverter');

  const invRows = [
    ['Selected Size', `${invKva} kVA`],
  ];
  if (invLabel) invRows.push(['Model', invLabel]);
  if (selectedInverter) {
    invRows.push(['Type', selectedInverter.type]);
    invRows.push(['Efficiency', `${selectedInverter.efficiency}%`]);
    invRows.push(['Max PV Input', `${selectedInverter.maxPvInputV}V`]);
    invRows.push(['MPPT Range', `${selectedInverter.mpptRangeMin}–${selectedInverter.mpptRangeMax}V`]);
  }
  invRows.push(['Required Size', `${formatNumber(calculations.requiredInverterKva, 1)} kVA`]);

  invRows.forEach(([label, value]) => {
    const pb = checkPageBreak(doc, y, 8, pageNum);
    y = pb.y;
    pageNum = pb.pageNum;
    drawKeyValue(doc, `${label}:`, value, MARGIN + 4, y, 50);
    y += 7;
  });

  y += 2;
  sep();

  sh('Charge Controller');

  if (project.hasBuiltInController) {
    drawKeyValue(doc, 'Type:', 'Built-in MPPT (Hybrid Inverter)', MARGIN + 4, y, 50);
    y += 7;
  } else {
    drawKeyValue(doc, 'Type:', 'External MPPT Controller', MARGIN + 4, y, 50);
    y += 7;
    drawKeyValue(doc, 'Required Size:', `${calculations.chargeControllerAmps || 0}A`, MARGIN + 4, y, 50);
    y += 7;
  }

  y += 2;
  sep();

  if (project.wireSectionEnabled && calculations.wires) {
    sh('Wire Sizing');

    const wireData = [
      { name: 'DC Array', data: calculations.wires.dcArray },
      { name: 'DC Battery', data: calculations.wires.dcBattery },
      { name: 'AC Output', data: calculations.wires.ac },
    ];

    wireData.forEach((w) => {
      if (!w.data) return;
      const pb = checkPageBreak(doc, y, 20, pageNum);
      y = pb.y;
      pageNum = pb.pageNum;

      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...TEAL);
      doc.text(w.name, MARGIN + 4, y);
      y += 6;

      drawKeyValue(doc, 'Current:', `${formatNumber(w.data.currentA, 2)}A`, MARGIN + 8, y, 40);
      y += 6;
      drawKeyValue(doc, 'Recommended:', `${w.data.recommendedMm2 || '—'} mm² (${w.data.recommendedAwg || '—'} AWG)`, MARGIN + 8, y, 40);
      y += 6;
      drawKeyValue(doc, 'Voltage Drop:', `${formatNumber(w.data.actualVoltageDropPct, 2)}%`, MARGIN + 8, y, 40);
      y += 8;
    });

    sep();
  }

  if (project.costSectionEnabled && calculations.costBreakdown && calculations.costBreakdown.length > 0 && calculations.totalCost > 0) {
    sh('Cost Estimation');

    const costRows = calculations.costBreakdown
      .filter(c => c.total > 0)
      .map(c => [
        c.item || c.label,
        `${c.quantity || ''}`,
        formatCurrency(c.unitPrice || c.unitCost || 0, project.currency),
        formatCurrency(c.total, project.currency),
      ]);

    const result = drawTable(doc, ['Item', 'Qty', 'Unit Price', 'Total'], costRows, y, pageNum);
    y = result.y;
    pageNum = result.pageNum;

    const pb = checkPageBreak(doc, y, 16, pageNum);
    y = pb.y;
    pageNum = pb.pageNum;

    doc.setFillColor(...TEAL);
    doc.rect(MARGIN + CONTENT_W / 2, y, CONTENT_W / 2, 12, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...DARK_BG);
    doc.text('TOTAL:', MARGIN + CONTENT_W / 2 + 6, y + 8);
    doc.text(formatCurrency(calculations.totalCost, project.currency), PAGE_W - MARGIN - 4, y + 8, { align: 'right' });

    y += 18;
  }

  addPageFooter(doc, pageNum);

  const filename = `${(project.projectName || 'solisys-report').replace(/[^a-zA-Z0-9-_]/g, '_')}.pdf`;
  doc.save(filename);
}
