import jsPDF from 'jspdf';

const TEAL = [0, 195, 201];
const DARK_BG = [9, 9, 11];
const SURFACE = [15, 15, 17];
const ELEVATED = [24, 24, 28];
const TEXT_PRIMARY = [240, 240, 245];
const TEXT_SECONDARY = [160, 160, 175];
const TEXT_MUTED = [100, 100, 115];
const BORDER = [40, 40, 48];
const WARNING_BG = [40, 35, 15];
const WARNING_BORDER = [180, 140, 20];

const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN = 20;
const CONTENT_W = PAGE_W - MARGIN * 2;

function fillPageBg(doc) {
  doc.setFillColor(...DARK_BG);
  doc.rect(0, 0, PAGE_W, PAGE_H, 'F');
}

function addPageFooter(doc, pageNum) {
  doc.setFontSize(8);
  doc.setTextColor(...TEXT_MUTED);
  doc.text('Generated by Solisys v2.0', MARGIN, PAGE_H - 10);
  doc.text(`Page ${pageNum}`, PAGE_W - MARGIN, PAGE_H - 10, { align: 'right' });
  doc.text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), PAGE_W / 2, PAGE_H - 10, { align: 'center' });
}

function checkPageBreak(doc, y, needed, pageNum) {
  if (y + needed > PAGE_H - 25) {
    addPageFooter(doc, pageNum);
    doc.addPage();
    pageNum++;
    fillPageBg(doc);
    return { y: MARGIN + 5, pageNum };
  }
  return { y, pageNum };
}

export function downloadInterpretationPDF(text, projectName) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  let y = 0;
  let pageNum = 1;

  fillPageBg(doc);

  doc.setFillColor(...SURFACE);
  doc.rect(0, 0, PAGE_W, 60, 'F');

  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...TEAL);
  doc.text('SOLISYS', PAGE_W / 2, 25, { align: 'center' });

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...TEXT_MUTED);
  doc.text('System Interpretation Report', PAGE_W / 2, 36, { align: 'center' });

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...TEXT_PRIMARY);
  doc.text(projectName || 'Untitled Project', PAGE_W / 2, 50, { align: 'center' });

  doc.setFillColor(...TEAL);
  doc.rect(0, 60, PAGE_W, 2, 'F');

  y = 72;

  const sections = text.split(/^## /m).filter(Boolean).map((block) => {
    const [title, ...rest] = block.split('\n');
    return { title: title.trim(), content: rest.join('\n').trim() };
  });

  sections.forEach((section) => {
    const pb = checkPageBreak(doc, y, 20, pageNum);
    y = pb.y;
    pageNum = pb.pageNum;

    doc.setFillColor(...TEAL);
    doc.rect(MARGIN, y, 3, 10, 'F');
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...TEAL);
    doc.text(section.title.toUpperCase(), MARGIN + 8, y + 8);
    y += 16;

    const paragraphs = section.content.split('\n\n').filter(Boolean);

    paragraphs.forEach((para) => {
      const isCallout = para.startsWith('Note:') || para.startsWith('Tip:');

      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');

      const maxWidth = isCallout ? CONTENT_W - 14 : CONTENT_W - 4;
      const lines = doc.splitTextToSize(para, maxWidth);
      const lineHeight = 4.5;
      const blockHeight = lines.length * lineHeight + 4;

      const pb2 = checkPageBreak(doc, y, blockHeight, pageNum);
      y = pb2.y;
      pageNum = pb2.pageNum;

      if (isCallout) {
        doc.setFillColor(...WARNING_BG);
        doc.rect(MARGIN + 2, y - 2, CONTENT_W - 4, blockHeight, 'F');
        doc.setFillColor(...WARNING_BORDER);
        doc.rect(MARGIN + 2, y - 2, 2, blockHeight, 'F');
        doc.setTextColor(...WARNING_BORDER);
        lines.forEach((line, i) => {
          doc.text(line, MARGIN + 10, y + 2 + i * lineHeight);
        });
      } else {
        doc.setTextColor(...TEXT_SECONDARY);
        lines.forEach((line, i) => {
          doc.text(line, MARGIN + 4, y + 2 + i * lineHeight);
        });
      }

      y += blockHeight + 2;
    });

    y += 4;

    doc.setDrawColor(...BORDER);
    doc.line(MARGIN, y, PAGE_W - MARGIN, y);
    y += 6;
  });

  addPageFooter(doc, pageNum);

  const filename = `${(projectName || 'solisys-interpretation').replace(/[^a-zA-Z0-9-_]/g, '_')}_interpretation.pdf`;
  doc.save(filename);
}
